<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Minas Metálica - Comercial</title>
    <link rel="icon" href="/images/logo" type="image/x-icon" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    <?php require __DIR__ . "/../../styles/default.html"; ?>
    <?php require __DIR__ . "/../../actions/config.html" ?>
</head>
<body onload="showComercial()">
    <?php require __DIR__ . "/../header.html" ?>
    <?php require __DIR__ . "/structs/comercial/principal.phtml" ?>
    <?php require __DIR__ . "/../footer.html" ?>
</body>

<script type="text/javascript">
    let ajustaLink= document.getElementsByClassName("nav-link")
    for (const key in ajustaLink) {
        ajustaLink[key].className="nav-link"
    }
    for (const key2 in ajustaLink) {
        if(ajustaLink[key2].innerHTML == "Galeria"){
            ajustaLink[key2].className="nav-link active"
        }
    }
</script>
</html>