<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Minas Metálica - Apresentacao</title>
    <link rel="icon" type="image/png" href="/images/logo"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    <?php require __DIR__ . "/styles/default.html"; ?>
    <?php require __DIR__ . "/actions/config.html" ?>
</head>
<body onload="apresentar()" id="bodyApresentacao">
    <div class="row w-100 m-0 h-100 text-white justify-content-center align-items-center" style="height: 100vh !important">
        
            <div id="logoapresentacao" class="row">
            <div class="col-3 col-lg-4"></div>
            <div class="col-6 col-lg-4">
                <div class="row">
                    <div class="col-12 text-center"><img src="/images/logo" class="img-fluid"></div>
                    <div class="col-12 text-left">
                        <h4 class="gold pt-4">Transformando Aço em Sonhos</h1>
                    </div>
                </div>
            </div>
            <div class="col-3 col-lg-4"></div>
    </div>
    </div>
</body>
</html>